/*
  HASH TABLES

  Summary:
  A key - value store system where values are stored into a table, accessible
  by keys generated by a hash function. The hash function calcualtes the best
  index that the item should go in, such that it is within the bounds of the
  underlying array and without overwriting existing data in this array. The
  benefits are that one can find data by calculating an index rather than
  searching, which is what makes hash tables so fast.



*/

import java.util.Arrays;

public class Main {

  public static void main(String[] args){

    HashTable ht = new HashTable(31);
    String[] elementsToAdd = {"35", "79", "168", "112", "309", "64", "1", "22",
      "17", "225", "326", "984", "320", "415", "999", "50", "660", "722", "413",
      "170", "989", "320", "268", "400", "978"};
    ht.hashFunction(elementsToAdd);
    ht.displayTheStack();
  }

}
